global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: spring
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]