global:
  scrape_interval: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]